name: convert_scel2rime_dict

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"   # 设置定时任务

jobs:
  convert_scel2rime_dict:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: "3.11"  # 你可以根据需要选择 Python 版本
          cache: pip

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pypinyin pypinyin_dict

      - name: Download sogou scel file
        run: |
          curl -fsL -o sogou_pop.scel 'https://pinyin.sogou.com/d/dict/download_cell.php?id=4&name=网络流行新词【官方推荐】&f=detail'

      - name: Convert sogou scel to rime quanpin_dict
        run: |
          python3 ./tools/scel2rime.py sogou_pop.scel

      - name: Gen diff_sg.txt
        run: |
          awk -F'\t' 'FNR==NR&&NR>=10{a[$1]++;w[$1]=$0};FNR!=NR&&FNR>=10{b[$1]++}END{for(i in a){if(b[i]<1)print w[i]}}' ./dicts/sogou_pop.dict.yaml ./dicts/moss.sogou_pop.dict.yaml >diff_sg.txt

      - name: Convert diff_sg.txt to dict
        run: |
          python3 ./tools/convert_diff_to_dict.py

      - name: Gen moss dict
        run: |
          python3 ./tools/04-gen_moss_tiger_dict.py ./moss.sogou_pop.dict.yaml --moss ./dicts/moss.base.dict.yaml --dict ./diff_sg.dict.yaml

      - name: Merge moss.sogou_pop.dict.yaml
        run: |
          python3 ./tools/merge_sogou_pop_dicts.py

      - name: Remove intermediate file
        run: |
          rm -f ./diff_sg* ./moss.sougou_pop.dict.yaml

      - name: Set env
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        run: |
          git add dicts/moss.sogou_pop.dict.yaml
          git commit -m "convert_scel2rime_dict"
          git push origin main